// Generated by CoffeeScript 1.3.3
(function() {

  window.AddActionCtrl = [
    '$scope', '$modalInstance', 'action', function(self, $modalInstance, action) {
      self.action = _.clone(action);
      self.ok = function() {
        return $modalInstance.close(self.action);
      };
      return self.cancel = function() {
        return $modalInstance.dismiss('cancel');
      };
    }
  ];

}).call(this);
