// Generated by CoffeeScript 1.3.3
(function() {

  window.appCtrl = [
    '$rootScope', '$filter', function(self, $filter) {
      var stored;
      self.companies = ['Google', 'Blah-blah', 'IBM', 'HP'];
      self.well_numbers = [
        {
          name: 'Well-01',
          region: 'South',
          state: 'Oklahoma',
          office: 'Ringwood'
        }, {
          name: 'Well-02',
          region: 'North',
          state: 'Montana',
          office: 'Sidney'
        }, {
          name: 'Well-03',
          region: 'North',
          state: 'Dakota',
          office: 'Tioga'
        }
      ];
      self.severities = ['Loss of well control', 'Fatality(ies)', 'Hospitalization or medical treatment', 'Spill offsite > 50 Bbls', 'Spill to water, any amount', 'Property damage'];
      self.fields = [
        {
          label: 'Date and Time of Incident',
          key: 'date',
          required: true
        }, {
          label: 'Reported By',
          key: 'reporter',
          required: true
        }, {
          label: 'Company of Reporter',
          key: 'reporter_company',
          required: true
        }, {
          label: 'Contact Number',
          key: 'contact',
          required: true
        }, {
          label: 'Supervisor Name',
          key: 'supervisor'
        }, {
          label: 'High Level Description of Incident',
          key: 'description',
          required: true
        }, {
          label: 'Well Number',
          key: 'well_number',
          required: true
        }, {
          label: 'Region',
          key: 'region'
        }, {
          label: 'State',
          key: 'state'
        }, {
          label: 'Field Office',
          key: 'office'
        }, {
          label: 'Incident Severity (Check all that Apply)',
          key: 'severities',
          required: true
        }
      ];
      stored = localStorage['incident'];
      self.incident = {
        disale_severity: false,
        reporter_company: '',
        severities: [],
        actions: [],
        isValid: function() {
          var field, _i, _len, _ref;
          _ref = self.fields;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            field = _ref[_i];
            if (field.required && !this[field.key]) {
              return false;
            }
          }
          return true;
        },
        getValue: function(key) {
          if (this[key]) {
            switch (key) {
              case 'date':
                return $filter('date')(this.date, 'MM/dd/yyyy HH:mm a');
              default:
                return this[key];
            }
          }
        }
      };
      stored = localStorage['incident'];
      if (stored) {
        return self.incident = _.assign(self.incident, $.parseJSON(stored));
      } else {
        return console.log('storage can not be used');
      }
    }
  ];

}).call(this);
