// Generated by CoffeeScript 1.3.3
(function() {

  app.directive('formatteddate', function($filter) {
    return {
      link: function(scope, element, attrs, ctrl) {
        ctrl.$formatters.unshift(function(modelValue) {
          return $filter('date')(modelValue, 'MM/dd/yyyy HH:mm a');
        });
        return ctrl.$parsers.unshift(function(viewValue) {
          return $filter('date')(viewValue, 'MM/dd/yyyy HH:mm a');
        });
      },
      restrict: 'A',
      require: 'ngModel'
    };
  });

}).call(this);
